config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks:  "users/omniauth_callbacks"
                     }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓addressの登録ページ
    get "users/new_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/new_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/new_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end

  resources :users, only: [:show] do
    collection do
      get "card"
      get "selling"
      get "selling_progress"
      get "sold"
      get "bought_progress"
      get "bought_past"
    end
  end

  resources :items  do
    member do
      get "purchase_confirmation"
      post "purchase"
    end
    collection do
      get "search"
      get "scraping_category"
      get "scraping_autobike"
      get "scraping_car_parts"
      get "scraping_cosme"
      get "scraping_domestic_car"
      get "scraping_foods"
      get "scraping_forign_car"
      get "scraping_game"
      get "scraping_instrument"
      get "scraping_interior"
      get "scraping_kids"
      get "scraping_kitchen"
      get "scraping_ladies"
      get "scraping_mens"
      get "scraping_phone"
      get "scraping_sports"
      get "scraping_watch"
    end
  end
  resources :categories, only: [:index, :show]
  resource :cards, only: [:new, :create, :show, :update, :destroy]

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :cards, only: [:create,:destroy,:update], defaults: { format: 'json' }
    resources :categories, only: [:index], defaults: { format: 'json' } do
      collection do
        get "get_options"
      end
    end
    resources :brand_names, only: [:index], defaults: { format: 'json' }
    resources :size_groups, only: [:index], defaults: { format: 'json' }
  end
                     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google]

  has_one :address, dependent: :destroy
  has_one :sns_credential, dependent: :destroy
  has_one :card, dependent: :destroy

  has_many :items, foreign_key: "seller_id"
  has_many :dealings, foreign_key: "buyer_id"

  validates :nickname, :birthday, :earnings, :points, presence: true
  validates :first_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :last_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  private

  def self.find_oauth(auth)
    ## ↓既にsns_credentialのレコードがあるかを検索する。
    ## first_or_initialize→既にDBに存在するならDBから読み込む。無いなら新しく作る（newする）
    sns_credential = SnsCredential.where(uid: auth.uid, provider: auth.provider).first_or_initialize
    ## ↓①既にsns_credentialが登録済みのパターン
    ## ↓がomniauthコントローラのsession["devise.sns_auth"]に入る
    return {user: sns_credential.user, sns: sns_credential} if sns_credential.persisted?
    ## ↓まだsns_credentialが未登録の場合。
    ## 既にuserがemailで登録されているか調べる（例：googleでログインしようとしたが既にメールアドレスで新規登録済み）
    user = User.where(email: auth.info.email).first_or_initialize
    if user.persisted? ## ②sns_credentialは無いがuserは登録済みのパターン
      ## sns_credentialとuserを紐付ける。
      sns_credential.user_id = user.id
      sns_credential.save
    else ## ③sns_credentialとuserの両方が未登録のパターン
      user.nickname = auth.info.name
    end
    ## ↓がomniauthコントローラのsession["devise.sns_auth"]に入る
    return {user: user, sns: sns_credential}
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google
    callback_for(:google)
  end

  def callback_for(provider)
    ## find_oauthメソッドで既に登録されているかなどを調べる。返り値としてハッシュ形式でuserとsns_credentialをもらう。
    session["devise.sns_auth"] = User.find_oauth(request.env["omniauth.auth"])
    if session["devise.sns_auth"][:user].persisted? ## 登録済みだったらログイン
      sign_in_and_redirect session["devise.sns_auth"][:user], event: :authentication
    else ## まだ登録されていないなら新規登録画面へ飛ばす。
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :signed_up?
  layout 'no_menu'

  def select  ##登録方法の選択ページ
    @auth_text = "で登録する"
    session.delete(:"devise.sns_auth") if session["devise.sns_auth"]
  end

  # GET /resource/sign_up
  def new
    @progress = 1
    ## ↓sessionにsns認証のデータがある場合
    @user = User.new(session["devise.sns_auth"]["user"]) if session["devise.sns_auth"]
    ## ↓sessionにsns認証のデータがない場合
    super if !session["devise.sns_auth"]
  end

  # POST /resource
  def create
    redirect_to new_user_registration_path, alert: "reCAPTCHAを承認してください" and return unless verify_recaptcha
    if session["devise.sns_auth"] ## sessionがあるとき＝sns認証でここまできたとき
      ## パスワードが未入力なのでランダムで生成する
      pass = Devise.friendly_token[8,12]
      ## 生成したパスワードをparamsに入れる
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
      sns = SnsCredential.new(session["devise.sns_auth"]["sns"])
    end
    ## ↓は@user = User.new(sign_up_params)と同じ
    build_resource(sign_up_params)
    ## save出来るか予めチェック
    unless resource.valid? ## 登録に失敗したとき
      ## 進捗バー用の@progressとflashメッセージをセットして戻る
      @progress = 1
      flash.now[:alert] = resource.errors.full_messages
      render :new and return
    end
    ## sessionに後々saveするuserを入れておく
    session["devise.regist_data"] = {user: @user.attributes}
    ## ↑だけだと後々passwordが空になってしまうので↓を入れておく
    session["devise.regist_data"][:encrypted_password] = nil
    session["devise.regist_data"][:user][:password] = params[:user][:password]
    redirect_to confirm_phone_path
  end

  def confirm_phone ## userのcreateに成功したらここに来る
    @progress = 2
  end

  def new_address ## 電話番号認証ページのボタンを押したらここに来る
    ## address登録済の時はリダイレクト
    redirect_to new_regist_payment_path if session["devise.regist_data"][:address] || current_user&.address
    @progress = 3
    @address = Address.new
  end

  def create_address
    @address = Address.new(address_params)
    if @address.valid? ## バリデーションに引っかからない（save可能な）時
      session["devise.regist_data"][:address] = @address
      redirect_to new_regist_payment_path
    else  ## バリデーションに引っかかる（save不可な）時
      redirect_to new_regist_address_path, alert: @address.errors.full_messages
    end
  end

  def new_payment
    ## card登録済の時はリダイレクト
    redirect_to regist_completed_path and return if session["devise.regist_data"][:card] || current_user&.card
    @progress = 4
    @card = Card.new
    render template: "cards/new"
  end

  def completed
    redirect_to root_path, alert: "エラーが発生しました" unless session["devise.regist_data"]
    @progress = 5
    @user = build_resource(session["devise.regist_data"]["user"])
    @user.build_sns_credential(session["devise.sns_auth"]["sns"]) if session["devise.sns_auth"] ## sessionがあるとき＝sns認証でここまできたとき
    @user.build_address(session["devise.regist_data"]["address"])
    @user.build_card(session["devise.regist_data"]["card"])
    if @user.save
      sign_up(resource_name, resource)  ## ログインさせる
    else
      redirect_to root_path, alert: @user.errors.full_messages
    end
  end

  private

  def address_params
    params.require(:address).permit(:postal_code, :prefecture, :city, :house_number, :building_name, :phone_number)
  end

  def signed_up?
    redirect_to root_path, alert: "ログインしています。" if user_signed_in?
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  ## 新規登録成功後のページ
  def after_sign_up_path_for(resource)
    ## 電話番号認証ページのパスを指定
    confirm_phone_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'no_menu'

  def select
  end

  # GET /resource/sign_in
  def new
    @auth_text = "でログイン"
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'mypage'

  def show
  end

  def select_registration
    render layout: 'no_menu'
  end

  def selling  ## 出品した商品（販売中）
    @items = current_user.items.selling_items
  end

  def selling_progress ## 出品した商品（取引中）
    @items = current_user.items.selling_progress_items
  end

  def sold ## 出品した商品（売却済み）
    @items = current_user.items.sold_out_items
  end

  def bought_progress ## 購入した商品（取引中）
    @items = Item.bought_progress_items(current_user.id)
  end

  def bought_past ## 購入した商品（過去の取引）
    @items = Item.bought_past_items(current_user.id)
  end

  private
  def set_side_bar
    @lists1 =
      {text: "マイページ", path: '/users/1'},
      {text: "お知らせ", path: ""},
      {text: "いいね！一覧", path: ""},
      {text: "出品する", path: new_item_path},
      {text: "出品した商品---出品中", path: ""},
      {text: "出品した商品---取引中", path: ""},
      {text: "出品した商品---売却済", path: ""},
      {text: "購入した商品---取引中", path: ""},
      {text: "購入した商品---過去の取引", path: ""},
      {text: "ニュース一覧", path: ""},
      {text: "評価一覧", path: ""},
      {text: "ガイド", path: ""},
      {text: "お問い合わせ", path: ""}
    @lists2 =
      {text: "売上・振込申請", path: ""},
      {text: "ポイント", path: ""}
    @lists3 =
    {text: "プロフィール", path: ""},
    {text: "住所変更", path: ""},
    {text: "支払い方法", path: cards_path},
    {text: "メール/パスワード", path: ""},
    {text: "本人情報", path: ""},
    {text: "電話番号の確認", path: ""},
    {text: "ログアウト", path: destroy_user_session_path, method: "delete"}
  end

end

app/views/users/_bought_item.html.haml
.mypage-block
  .mypage-block-header
    = title
  .mypage-block-tabs
    = link_to bought_progress_users_path, class: "mypage-block-tabs__tab #{ 'active-tab' if active == 1 }" do
      取引中
    = link_to bought_past_users_path, class: "mypage-block-tabs__tab #{ 'active-tab' if active == 2 }" do
      過去の取引
  .mypage-block-data-list
    -if @items.length != 0
      = render partial: "users/item", collection: @items, locals:{subscript: subscript},  as: "item"
    -else
      .mypage-block-data-list__data-none
        .text
          商品がありません。

app/views/users/_item.html.haml
= link_to "" do
  .mypage-block-data-list__data
    .item-data
      = image_tag item.item_images[0].image.url, class: "item-data__image"
      .item-data__detail
        「
        = item.name
        」
        = subscript
      = image_tag "icon-arrow.png", class:"item-data__arrow"

app/views/users/_selling_item.html.haml
.mypage-block
  .mypage-block-header
    = title
  .mypage-block-tabs
    = link_to selling_users_path, class: "mypage-block-tabs__tab #{ 'active-tab' if active == 1 }" do
      出品中
    = link_to selling_progress_users_path, class: "mypage-block-tabs__tab #{ 'active-tab' if active == 2 }" do
      取引中
    = link_to sold_users_path, class: "mypage-block-tabs__tab #{ 'active-tab' if active == 3 }" do
      売却済み
  .mypage-block-data-list
    -if @items.length != 0
      = render partial: "users/item", collection: @items, locals:{subscript: subscript},  as: "item"
    -else
      .mypage-block-data-list__data-none
        .text
          商品がありません。

app/views/users/_side_bar.html.haml
.mypage-side-bar
  .mypage-side-bar-lists
    = render partial: 'users/side_bar_list', locals: {text: "マイページ", path: user_path(current_user), method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "お知らせ", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "いいね！一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品する", path: new_item_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---出品中", path: selling_users_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---取引中", path: selling_progress_users_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---売却済", path: sold_users_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "購入した商品---取引中", path: bought_progress_users_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "購入した商品---過去の取引", path: bought_past_users_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ニュース一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "評価一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ガイド", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "お問い合わせ", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      売上・ポイント
    = render partial: 'users/side_bar_list', locals: {text: "売上・振込申請", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ポイント", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      設定
    = render partial: 'users/side_bar_list', locals: {text: "プロフィール", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "住所変更", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "支払い方法", path: cards_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "メール/パスワード", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "本人情報", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "電話番号の確認", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ログアウト", path: destroy_user_session_path, method: "delete"}
  = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
    = image_tag "side_bar_banner.jpg", class: "side-bar-bottom"

app/views/users/_side_bar_list.html.haml
= link_to path, method: "#{method}" do
  .mypage-side-bar-lists__list
    .mypage-side-bar-lists__list--left
      = text
    .mypage-side-bar-lists__list--right
      = icon "fas", "chevron-right"

app/views/users/bought_past.html.haml
- breadcrumb :bought_past, current_user
= render  partial: 'users/bought_item', locals: {active: 2, title: "購入した商品--過去の取引", subscript: "を購入しました。取引済みです。"}

app/views/users/bought_progress.html.haml
- breadcrumb :bought_progress, current_user
= render  partial: 'users/bought_item', locals: {active: 1, title: "購入した商品--取引中", subscript: "を購入しました。取引中です。"}

app/views/users/selling.html.haml
- breadcrumb :selling, current_user
= render  partial: 'users/selling_item', locals: {active: 1, title: "出品した商品--販売中", subscript: "を出品中です。"}

app/views/users/selling_progress.html.haml
- breadcrumb :selling_progress, current_user
= render  partial: 'users/selling_item', locals: {active: 2, title: "出品した商品--取引中", subscript: "が購入されました。取引中です。"}

app/views/users/show.html.haml
- breadcrumb :user_show, current_user
= render 'layouts/bread_crumbs'
.mypage-block
  .mypage-block-header-user
    =link_to " " do
      =image_tag "user_noimage.png", class:"mypage-block-header-user__image"
      .mypage-block-header-user__name
        = current_user.nickname
      .mypage-block-header-user__rate
        評価：５ 出品数 3
  .mypage-block-tabs
    .mypage-block-tabs__tab.active-tab
      取引中
    .mypage-block-tabs__tab
      過去の取引
  .mypage-block-data-list
    .mypage-block-data-list__data-none
      .text
        出品中の商品がありません。
.mypage-block
  .mypage-block-header
    出品した商品
  .mypage-block-tabs
    .mypage-block-tabs__tab.active-tab
      取引中
    .mypage-block-tabs__tab
      過去の取引
  .mypage-block-data-list
    .mypage-block-data-list__data-none
      .text
        出品中の商品がありません。

app/views/users/sold.html.haml
- breadcrumb :sold, current_user
= render  partial: 'users/selling_item', locals: {active: 3, title: "出品した商品--売却済み", subscript: "は売却済みです。"}