config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks:  "users/omniauth_callbacks"
                     }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓addressの登録ページ
    get "users/new_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/new_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/new_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end

  resources :users, only: [:show] do
    collection do
      get "card"
      get "selling"
      get "selling_progress"
      get "sold"
      get "bought_progress"
      get "bought_past"
    end
  end

  resources :items  do
    member do
      get "purchase_confirmation"
      post "purchase"
    end
    collection do
      get "search"
      get "scraping_category"
      get "scraping_autobike"
      get "scraping_car_parts"
      get "scraping_cosme"
      get "scraping_domestic_car"
      get "scraping_foods"
      get "scraping_forign_car"
      get "scraping_game"
      get "scraping_instrument"
      get "scraping_interior"
      get "scraping_kids"
      get "scraping_kitchen"
      get "scraping_ladies"
      get "scraping_mens"
      get "scraping_phone"
      get "scraping_sports"
      get "scraping_watch"
    end
  end
  resources :categories, only: [:index, :show]
  resource :cards, only: [:new, :create, :show, :update, :destroy]

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :cards, only: [:create,:destroy,:update], defaults: { format: 'json' }
    resources :categories, only: [:index], defaults: { format: 'json' } do
      collection do
        get "get_options"
      end
    end
    resources :brand_names, only: [:index], defaults: { format: 'json' }
    resources :size_groups, only: [:index], defaults: { format: 'json' }
  end
                     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true

  validates :customer_token, presence: true

  private
  def self.regist_customer(card_token, email)  ## カードのトークンを渡して顧客のトークンをもらいDBに登録する。
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    return nil unless card_token  ## カードのトークンが無い場合、nilを返してリダイレクトさせる。
    customer = Payjp::Customer.create(  ## 顧客の作成
    email: email,
    card: card_token
    )
    return customer
  end

  def self.get_card(customer_token)  ## カード情報を取得する。支払い方法ページで使用する。
    return nil unless customer_token
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    customer = Payjp::Customer.retrieve(customer_token)
    card = {}
    card_data = customer.cards.retrieve(customer.default_card)
    card[:last4] = "************" + card_data.last4
    card[:exp_month]= card_data.exp_month
    card[:exp_year] = card_data.exp_year - 2000
    card[:brand] = card_data.brand
    return card
  end

  def self.get_customer(customer_token)  ## 顧客情報を取得する。これを使って支払いをする。
    return nil unless customer_token
    customer = Payjp::Customer.retrieve(customer_token)
  end

end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update]  ## ログイン必須のアクション

  def create #payjpにカード情報を登録
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id} #なくてもOK
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def update  ## カードの更新
    customer = Payjp::Customer.create(
        email: current_user.email,
        card: params[:token],
        metadata: {user_id: current_user.id}
    )
    @card_data = current_user.card.update(card_token:customer.id)
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  layout 'mypage'
  before_action :authenticate_user!, except: [:create]

  def show
    @card = Card.get_card(current_user.card&.customer_token)
    render layout: 'mypage'
  end

  def new
    redirect_back(fallback_location: regist_completed_path) if current_user.card ## 既にカードを登録しているならリダイレクト
    @progress = 4
    @card = Card.new
  end

  def create #データベースにカードのcustomerのtokenを保存する。
    email = current_user.email if user_signed_in?  ## マイページのカード登録画面から遷移してきた場合
    email = session["devise.regist_data"]["user"]["email"] if session["devise.regist_data"] ## 新規ユーザー登録画面から遷移してきた場合
    # params[:card_token]に「tok_hogehoge」という形でカードのトークンが送られてきている
    # ↑このトークンはjsの方でappendしたhidden_fieldに埋め込まれていたもの
    customer = Card.regist_customer(params[:card_token], email) ## customerを作成
    @card = Card.new(customer_token: customer&.id)
    redirect_to action: "new", alert: "カードの登録に失敗しました。" and return if @card.invalid? ## カードの保存に失敗した場合
    ## 保存に成功した場合
    before_controller = Rails.application.routes.recognize_path(request.referer)[:controller]
    ## ページの遷移元に応じてリダイレクト先を変更する。
    if before_controller == "users/registrations"
      ## 新規ユーザー登録画面から遷移してきた場合、登録完了画面へ遷移
      session["devise.regist_data"][:card] = @card
      redirect_to regist_completed_path and return
    end
    ## マイページの支払い方法ページから遷移してきた場合、支払い方法ページへ遷移
    @card.user_id = current_user.id
    @card.save
    redirect_to cards_path and return
  end

  def destroy
    @card = current_user.card
    @card.destroy
    redirect_to cards_path
  end

end

app/views/cards/new.html.haml
-if user_signed_in?
  - breadcrumb :card_new, current_user
.block.horizontal-padding-25
  .block__menu
    支払い方法
.block.horizontal-padding-25
  = form_with model: @card, id: "card_form" do |f|
    .input-field
      .input-field-main
        = f.label :card_number, "カード番号"
        %span.required-true
          必須
        %br
        = f.text_field :card_number, required: true, maxlength: 16, id: "card_number_form", placeholder: "1234 5678 1234 5678"
        #card-icons
          = image_tag 'icon_visa.png'
          = image_tag 'icon_master.jpg'
          = image_tag 'icon_saison.png'
          = image_tag 'icon_jcb.png'
          = image_tag 'icon_american.svg'
          = image_tag 'icon_diners.png'
          = image_tag 'icon_discover.png'
    .input-field
      .input-field-main
        = f.label :exp_month, "有効期限"
        %span.required-true
          必須
        .input-field-multiple
          = f.select :exp_month, options_for_select((1..12)), {include_blank: "---"}, id: "exp_month_form"
          .input-field-multiple__separate-text
            月
          = f.select :exp_year, options_for_select((Date.today.year%100..Date.today.year%100 + 10)), {include_blank: "---"}, id: "exp_year_form"
          .input-field-multiple__separate-text
            年
    .input-field
      .input-field-main
        = f.label :security, "セキュリティコード"
        %span.required-true
          必須
        %br
        = f.text_field :security, required: true,  id: "cvc_form", placeholder: "カード背面４桁もしくは３桁の番号"
        %br
        .information
          .information__right.font-skyblue
            = icon "fas", "question-circle", class:"header-bottom-left__button--red"
            カード裏面の番号とは？
        #card_token
    = f.submit "次へ進む", class:"button back-red font-white", id: "regist_card"

app/views/cards/show.html.haml
- breadcrumb :card_show, current_user
.block
  .block__menu
    支払い方法
.block
  .block__menu
    クレジットカード一覧
  -if current_user.card
    .block__main
      .card-show.horizontal-padding-25
        .card-show__data
          = image_tag 'icon_visa.png'
          = @card[:last4]
          %br
          = @card[:exp_month]
          \/
          = @card[:exp_year]
          %br
          = @card[:brand]
        =link_to "削除する", cards_path, method: :delete, class: "delete-button"
  -else
    .block__main.horizontal-padding-25
      = link_to new_cards_path, data: {turbolinks: false} do
        .button.regist-card
          = icon "far", "credit-card"
          %span.button__text
            新規登録
.block
  .block__main
    = link_to "支払い方法について >", root_path