config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks:  "users/omniauth_callbacks"
                     }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓addressの登録ページ
    get "users/new_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/new_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/new_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end

  resources :users, only: [:show] do
    collection do
      get "card"
      get "selling"
      get "selling_progress"
      get "sold"
      get "bought_progress"
      get "bought_past"
    end
  end

  resources :items  do
    member do
      get "purchase_confirmation"
      post "purchase"
    end
    collection do
      get "search"
      get "scraping_category"
      get "scraping_autobike"
      get "scraping_car_parts"
      get "scraping_cosme"
      get "scraping_domestic_car"
      get "scraping_foods"
      get "scraping_forign_car"
      get "scraping_game"
      get "scraping_instrument"
      get "scraping_interior"
      get "scraping_kids"
      get "scraping_kitchen"
      get "scraping_ladies"
      get "scraping_mens"
      get "scraping_phone"
      get "scraping_sports"
      get "scraping_watch"
    end
  end
  resources :categories, only: [:index, :show]
  resource :cards, only: [:new, :create, :show, :update, :destroy]

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :cards, only: [:create,:destroy,:update], defaults: { format: 'json' }
    resources :categories, only: [:index], defaults: { format: 'json' } do
      collection do
        get "get_options"
      end
    end
    resources :brand_names, only: [:index], defaults: { format: 'json' }
    resources :size_groups, only: [:index], defaults: { format: 'json' }
  end
                     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_bread_crumbs.html.haml
- if controller.action_name != "index" || controller.controller_name != "items"
  .breadcrumbs-wrapper.horizontal-padding-15
    = breadcrumbs pretext: "", separator: " &rsaquo; "

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_footer.html.haml
%footer.footer
  .footer-top.horizontal-padding-15
    .footer-top-left
      .footer-top-left__top
        スマホでかんたんフリマアプリ
      .footer-top-left__bottom
        今すぐ無料ダウンロード！
      .footer-top-left__images
        = image_tag 'mercari_icon.png', class: "footer-top-left__images--mercari"
        = image_tag 'app-store.svg', class: "footer-top-left__images--phone"
        = image_tag 'google-play.svg', class: "footer-top-left__images--phone"
    =image_tag 'footer_phone.png', class: "footer-top-right"
  .footer-middle.horizontal-padding-15
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        メルカリについて
      .footer-middle-wrapper__bottom
        = link_to '会社概要（運営会社）' , '/'
        = link_to '採用情報' , '/'
        = link_to '公式ブログ' , '/'
        = link_to 'メルカリロゴ利用ガイドライン' , '/'
        %p
          = icon "fab", "twitter"
          = icon "fab", "facebook-square"
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        ヘルプ＆ガイド
      .footer-middle-wrapper__bottom
        = link_to 'メルカリガイド' , '/'
        = link_to 'らくらくメルカリ便' , '/'
        = link_to '大型メルカリ便' , '/'
        = link_to '車体取引ガイド' , '/'
        = link_to 'メルカリあんしん・あんぜん宣言！' , '/'
        = link_to '偽ブランド品撲滅への取り組み' , '/'
        = link_to 'メルカリボックス' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        プライバシーと利用規約
      .footer-middle-wrapper__bottom
        = link_to 'プライバシーポリシー' , '/'
        = link_to 'メルカリ利用規約' , '/'
        = link_to 'あんしんスマホサポート制度に関する利用特約' , '/'
        = link_to 'コンプライアンスポリシー' , '/'
        = link_to '偽ブランド品撲滅への取り組み' , '/'
        = link_to 'メルカリボックス' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
      .footer-middle-wrapper__bottom
        = link_to '個人データの安全管理に係る基本方針' , '/'
        = link_to '特定商取引に関する表記' , '/'
        = link_to '資金決済法に基づく表示' , '/'
        = link_to '法令順守と犯罪抑止のために' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        国
      .footer-middle-wrapper__bottom
        = link_to '日本' , '/'
        = link_to 'United States' , '/'
  .footer-bottom.horizontal-padding-15
    .footer-bottom__logo-copyright
      = image_tag 'logo-white.svg', class: "footer-bottom__logo-copyright--logo"
      %span.footer-bottom__logo-copyright--copyright
        © 2019 Mercari

app/views/layouts/_header.html.haml
%header.header.horizontal-padding-15
  .header-top
    = link_to root_path do
      = image_tag 'logo.svg', class: "header-top__logo"
    = form_with url: search_items_path, method: :get, local: true  do |f|
      = f.search_field :name, name: "name_search", placeholder: "何かお探しですか?", class: "header-top__search"
      = f.hidden_field :name, name: "q[:hoge]"
      = button_tag type: 'submit', class:"header-top__loupe" do
        = icon "fas", "search"
  .header-bottom
    .header-bottom-left
      .header-bottom-left__button
        = link_to categories_path do
          = icon "fas", "list", class:"header-bottom-left__button--red"
          カテゴリーから探す
        .category-lists
          .category-lists__list
            - Category.roots.each do |parent_category|
              = link_to category_path(parent_category), class:"category-lists__list--category", data: {category_id: parent_category.id} do
                = parent_category.name
              .category-lists__list.child
                - parent_category.get_children.each do |child_category|
                  = link_to category_path(child_category), class:"category-lists__list--category", data: {category_id: child_category.id} do
                    = child_category.name
                  .category-lists__list.child
                    - child_category.get_children.each do |grandchild_category|
                      = link_to category_path(grandchild_category), class:"category-lists__list--category", data: {category_id: grandchild_category.id} do
                        = grandchild_category.name
      .header-bottom-left__button
        = link_to "" do
          = icon "fas", "tags", class:"header-bottom-left__button--red"
          ブランドから探す
    .header-bottom-right
      - if user_signed_in?
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "heart", class:"header-bottom-right__button--gray"
            いいね!一覧
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "bell", class:"header-bottom-right__button--gray"
            お知らせ
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "check", class:"header-bottom-right__button--gray"
            やることリスト
        .header-bottom-right__button
          = link_to user_path(1) do
            = image_tag 'user_noimage.png', class:"header-bottom-right__mypage"
            マイページ
      - else
        = link_to select_registration_path,  data: {turbolinks: :false} do
          新規会員登録
        = link_to new_user_session_path, data: {turbolinks: :false}  do
          ログイン
= render 'layouts/bread_crumbs'

app/views/layouts/_select_auth.html.haml
.block.horizontal-padding-25
  -# コントローラがsessionsではないならメールアドレスで○○○は表示しない
  - if controller.controller_name != "sessions"
    = link_to new_user_registration_path do
      .button.mail
        = icon "far", "envelope", class: "button__mail-icon"
        %span.button__text
          -# @auth_textには「で登録する」や「でログイン」が入る
          メールアドレス#{@auth_text}
  = link_to user_facebook_omniauth_authorize_path do
    .button.facebook
      = icon "fab", "facebook-square", class: "button__facebook-icon"
      %span.button__text
        facebook#{@auth_text}
  = link_to user_google_omniauth_authorize_path, method: :post do
    .button.google
      = image_tag "google_icon.png", class: "button__google-icon"
      %span.button__text
        Google#{@auth_text}

app/views/layouts/_sold_out.html.haml
-if item.deal != "販売中"
  .sold-out
    .sold-out__text
      SOLD

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSecond
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'layouts/flash'
  = render 'layouts/header'
  = yield
  = link_to new_item_path, data:{turbolinks: false} do
    .sell-button
      .sell-button__text
        出品
      = icon "fas", "camera", class:"sell-button__icon"
  = render 'layouts/footer'

app/views/layouts/mypage.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSecond
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
%body
  = render 'layouts/flash'
  = render 'layouts/header'
  .mypage.horizontal-padding-15
    = render 'users/side_bar'
    .mypage-main
      = yield
  = link_to new_item_path, data:{turbolinks: false} do
    .sell-button
      .sell-button__text
        出品
      = icon "fas", "camera", class:"sell-button__icon"
  = render 'layouts/footer'

app/views/layouts/no_menu.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSecond
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
%body
  = render 'layouts/flash'
  .horizontal-padding-25
    %header.header-no-menu
      = link_to root_path do
        = image_tag 'top-logo.svg', class: "logo"
      -if @progress
        .progress-bar
          .progress
            .progress-title{class: "#{'doing' if @progress == 1}"}
              会員情報
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 1}"}
              .progress-node__line{class: "#{'done' if @progress >= 2}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 2}"}
              電話番号認証
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 2}"}
              .progress-node__line{class: "#{'done' if @progress >= 3}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 3}"}
              お届け先住所入力
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 3}"}
              .progress-node__line{class: "#{'done' if @progress >= 4}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 4}"}
              支払い方法
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 4}"}
              .progress-node__line{class: "#{'done' if @progress >= 5}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 5}"}
              完了
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 5}"}
    = yield
    %footer.footer-no-menu
      %nav
        %ul
          = link_to "" do
            %li
              プライバシーポリシー
          = link_to "" do
            %li
              メルカリ利用規約
          = link_to "" do
            %li
              特定商取引に関する表記
      = image_tag 'bottom-logo.svg', class: "logo"